import type { Plugin } from 'vite';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  unlinkSync,
  writeFileSync
} from 'fs';
import { basename, join } from 'path';
import { discoverComponents } from './component-discovery.ts';
import { generateSectionLiquid, isAutoGenerated } from './liquid-template.ts';
import { toKebabCase } from './liquid-schema.ts';
import { fragmentInjection, invalidateFragmentCache } from '../vite-fragment-injection.ts';

export interface LiquidSyncOptions {
  componentsDir?: string;
  snippetsSrcDir?: string;
  fragmentsDir?: string;
  sectionsOutDir?: string;
  snippetsOutDir?: string;
  verbose?: boolean;
}

const SECTION_PREFIX = 'section.';
const SNIPPET_PREFIX = 'snippet.';

function ensureDir(directory: string): void {
  if (!existsSync(directory)) mkdirSync(directory, { recursive: true });
}

function writeIfChanged(filePath: string, content: string): boolean {
  if (existsSync(filePath) && readFileSync(filePath, 'utf-8') === content) {
    return false;
  }

  ensureDir(join(filePath, '..'));
  writeFileSync(filePath, content, 'utf-8');
  return true;
}

function collectLiquidFiles(directory: string, found: string[] = []): string[] {
  if (!existsSync(directory)) return found;

  for (const entry of readdirSync(directory)) {
    const fullPath = join(directory, entry);

    if (statSync(fullPath).isDirectory()) {
      collectLiquidFiles(fullPath, found);
    } else if (entry.endsWith('.liquid')) {
      found.push(fullPath);
    }
  }

  return found;
}

function stripPrefix(fileName: string, prefix: string): string {
  return fileName.startsWith(prefix) ? fileName.slice(prefix.length) : fileName;
}

function outputNameFor(filePath: string, prefix: string): string {
  return stripPrefix(basename(filePath, '.liquid'), prefix);
}

export function liquidSync(options: LiquidSyncOptions = {}): Plugin {
  const {
    componentsDir = 'src/components',
    snippetsSrcDir = 'src/snippets',
    fragmentsDir = 'src/utils/schema-fragments',
    sectionsOutDir = 'sections',
    snippetsOutDir = 'snippets',
    verbose = true
  } = options;

  function log(message: string): void {
    if (verbose) console.log(`[reactpify] ${message}`);
  }

  function generateSectionSources(): Set<string> {
    const generatedNames = new Set<string>();

    for (const component of discoverComponents(componentsDir)) {
      const { analysis, directory, filePath } = component;
      const sectionName = toKebabCase(analysis.componentName);
      const sectionPath = join(directory, `${SECTION_PREFIX}${sectionName}.liquid`);

      generatedNames.add(sectionName);

      if (existsSync(sectionPath) && !isAutoGenerated(readFileSync(sectionPath, 'utf-8'))) {
        continue;
      }

      const content = generateSectionLiquid(analysis, filePath.replace(/\\/g, '/'));

      if (writeIfChanged(sectionPath, content)) {
        log(`section source generated: ${sectionPath}`);
      }
    }

    return generatedNames;
  }

  async function copyLiquid(
    sourceFiles: string[],
    prefix: string,
    outDir: string,
    label: string
  ): Promise<Set<string>> {
    ensureDir(outDir);
    const copiedNames = new Set<string>();

    for (const sourceFile of sourceFiles) {
      const outputName = outputNameFor(sourceFile, prefix);
      const outputPath = join(outDir, `${outputName}.liquid`);
      const content = await fragmentInjection(readFileSync(sourceFile, 'utf-8'));

      copiedNames.add(outputName);

      if (writeIfChanged(outputPath, content)) {
        log(`${label} updated: ${outputPath}`);
      }
    }

    return copiedNames;
  }

  function removeOrphans(outDir: string, keepNames: Set<string>): void {
    if (!existsSync(outDir)) return;

    for (const entry of readdirSync(outDir)) {
      if (!entry.endsWith('.liquid')) continue;

      const name = basename(entry, '.liquid');
      if (keepNames.has(name)) continue;

      const fullPath = join(outDir, entry);
      if (!isAutoGenerated(readFileSync(fullPath, 'utf-8'))) continue;

      unlinkSync(fullPath);
      log(`removed orphaned file: ${fullPath}`);
    }
  }

  async function sync(): Promise<void> {
    invalidateFragmentCache();
    generateSectionSources();

    const sectionSources = collectLiquidFiles(componentsDir).filter((file) =>
      basename(file).startsWith(SECTION_PREFIX)
    );
    const snippetSources = collectLiquidFiles(snippetsSrcDir);

    const sectionNames = await copyLiquid(
      sectionSources,
      SECTION_PREFIX,
      sectionsOutDir,
      'section'
    );
    await copyLiquid(snippetSources, SNIPPET_PREFIX, snippetsOutDir, 'snippet');

    removeOrphans(sectionsOutDir, sectionNames);
  }

  function watchedPaths(): string[] {
    return [
      ...collectLiquidFiles(componentsDir),
      ...collectLiquidFiles(snippetsSrcDir),
      ...collectLiquidFiles(fragmentsDir)
    ];
  }

  return {
    name: 'reactpify-liquid-sync',

    async buildStart() {
      await sync();

      for (const file of watchedPaths()) {
        this.addWatchFile(file);
      }
    },

    configureServer(server) {
      const sources = [componentsDir, snippetsSrcDir, fragmentsDir].filter(existsSync);
      server.watcher.add(sources);

      const handleChange = (file: string) => {
        if (!file.endsWith('.liquid') && !file.endsWith('.tsx')) return;
        if (file.includes(sectionsOutDir) || file.includes(snippetsOutDir)) return;

        void sync();
      };

      server.watcher.on('add', handleChange);
      server.watcher.on('change', handleChange);
      server.watcher.on('unlink', handleChange);
    }
  };
}
